
export const SLEK_LOGIN_STARTED = 'SLEK_LOGIN_STARTED';
export const SLEK_LOGIN_SUCCEEDED = 'SLEK_LOGIN_SUCCEEDED';
export const SLEK_LOGIN_FAILED = 'SLEK_LOGIN_FAILED';

export const SLEK_LOGOUT = 'SLEK_LOGOUT';


export const SLEK_CHANNELS_GETTING_STARTED = 'SLEK_CHANNELS_GETTING_STARTED';
export const SLEK_CHANNELS_GETTING_SUCCEEDED = 'SLEK_CHANNELS_GETTING_SUCCEEDED';
export const SLEK_CHANNELS_GETTING_FAILED = 'SLEK_CHANNELS_GETTING_FAILED';

export const SLEK_CHANNEL_CREATION_STARTED = 'SLEK_CHANNEL_CREATION_STARTED';
export const SLEK_CHANNEL_CREATION_SUCCEEDED = 'SLEK_CHANNEL_CREATION_SUCCEEDED';
export const SLEK_CHANNEL_CREATION_FAILED = 'SLEK_CHANNEL_CREATION_FAILED';

export const SLEK_CHANNEL_UPDATING_STARTED = 'SLEK_CHANNEL_UPDATING_STARTED';
export const SLEK_CHANNEL_UPDATING_SUCCEEDED = 'SLEK_CHANNEL_UPDATING_SUCCEEDED';
export const SLEK_CHANNEL_UPDATING_FAILED = 'SLEK_CHANNEL_UPDATING_FAILED';
export const SLEK_CHANNEL_EDITING_CANCELED = 'SLEK_CHANNEL_EDITING_CANCELED';
export const SLEK_CHANNEL_EDITING_STARTED = 'SLEK_CHANNEL_EDITING_STARTED';

export const SLEK_CHANNEL_DELETION_STARTED = 'SLEK_CHANNEL_DELETION_STARTED';
export const SLEK_CHANNEL_DELETION_SUCCEEDED = 'SLEK_CHANNEL_DELETION_SUCCEEDED';
export const SLEK_CHANNEL_DELETION_FAILED = 'SLEK_CHANNEL_DELETION_FAILED';

export const SLEK_CHANNEL_SELECTION_STARTED = 'SLEK_CHANNEL_SELECTION_STARTED';
export const SLEK_CHANNEL_SELECTION_SUCCEEDED = 'SLEK_CHANNEL_SELECTION_SUCCEEDED';
export const SLEK_CHANNEL_SELECTION_FAILED = 'SLEK_CHANNEL_SELECTION_FAILED';


export const SLEK_MESSAGE_CREATION_STARTED = 'SLEK_MESSAGE_CREATION_STARTED';
export const SLEK_MESSAGE_CREATION_SUCCEEDED = 'SLEK_MESSAGE_CREATION_SUCCEEDED';
export const SLEK_MESSAGE_CREATION_FAILED = 'SLEK_MESSAGE_CREATION_FAILED';

export const SLEK_MESSAGES_GETTING_STARTED = 'SLEK_MESSAGES_GETTING_STARTED';
export const SLEK_MESSAGES_GETTING_SUCCEEDED = 'SLEK_MESSAGES_GETTING_SUCCEEDED';
export const SLEK_MESSAGES_GETTING_FAILED = 'SLEK_MESSAGES_GETTING_FAILED';

export const SLEK_MESSAGE_DELETION_STARTED = 'SLEK_MESSAGE_DELETION_STARTED';
export const SLEK_MESSAGE_DELETION_SUCCEEDED = 'SLEK_MESSAGE_DELETION_SUCCEEDED';
export const SLEK_MESSAGE_DELETION_FAILED = 'SLEK_MESSAGE_DELETION_FAILED';

export const SLEK_MESSAGE_VOTE_UP_STARTED = 'SLEK_MESSAGE_VOTE_UP_STARTED';
export const SLEK_MESSAGE_VOTE_UP_SUCCEEDED = 'SLEK_MESSAGE_VOTE_UP_SUCCEEDED';
export const SLEK_MESSAGE_VOTE_UP_FAILED = 'SLEK_MESSAGE_VOTE_UP_FAILED';

export const SLEK_MESSAGE_VOTE_DOWN_STARTED = 'SLEK_MESSAGE_VOTE_DOWN_STARTED';
export const SLEK_MESSAGE_VOTE_DOWN_SUCCEEDED = 'SLEK_MESSAGE_VOTE_DOWN_SUCCEEDED';
export const SLEK_MESSAGE_VOTE_DOWN_FAILED = 'SLEK_MESSAGE_VOTE_DOWN_FAILED';


export const SLEK_ACCOUNT_CREATION_STARTED = 'SLEK_ACCOUNT_CREATION_STARTED';
export const SLEK_ACCOUNT_CREATION_SUCCEEDED = 'SLEK_ACCOUNT_CREATION_SUCCEEDED';
export const SLEK_ACCOUNT_CREATION_FAILED = 'SLEK_ACCOUNT_CREATION_FAILED';

export const SLEK_ACCOUNTS_GETTING_STARTED = 'SLEK_ACCOUNTS_GETTING_STARTED';
export const SLEK_ACCOUNTS_GETTING_SUCCEEDED = 'SLEK_ACCOUNTS_GETTING_SUCCEEDED';
export const SLEK_ACCOUNTS_GETTING_FAILED = 'SLEK_ACCOUNTS_GETTING_FAILED';

export const SLEK_ACCOUNT_GETTING_STARTED = 'SLEK_ACCOUNT_GETTING_STARTED';
export const SLEK_ACCOUNT_GETTING_SUCCEEDED = 'SLEK_ACCOUNT_GETTING_SUCCEEDED';
export const SLEK_ACCOUNT_GETTING_FAILED = 'SLEK_ACCOUNT_GETTING_FAILED';

export const SLEK_ACCOUNT_AUTHORIZATION_FAILED = 'SLEK_ACCOUNT_AUTHORIZATION_FAILED';
