
export const SLEK_LOGIN = 'SLEK_LOGIN';
export const SLEK_LOGIN_SUCCESS = 'SLEK_LOGIN_SUCCESS';
export const SLEK_LOGIN_FAILURE = 'SLEK_LOGIN_FAILURE';

export const SLEK_LOGOUT = 'SLEK_LOGOUT';
export const SLEK_LOGOUT_SUCCESS = 'SLEK_LOGOUT_SUCCESS';
export const SLEK_LOGOUT_FAILURE = 'SLEK_LOGOUT_FAILURE';

export const SLEK_CHANNELS_MOUNTED = 'SLEK_CHANNELS_MOUNTED';
export const SLEK_GET_CHANNELS_SUCCESS = 'SLEK_GET_CHANNELS_SUCCESS';
export const SLEK_GET_CHANNELS_FAILURE = 'SLEK_GET_CHANNELS_FAILURE';

export const SLEK_ADD_CHANNEL = 'SLEK_ADD_CHANNEL';
export const SLEK_ADD_CHANNEL_SUCCESS = 'SLEK_ADD_CHANNEL_SUCCESS';
export const SLEK_ADD_CHANNEL_FAILURE = 'SLEK_ADD_CHANNEL_FAILURE';


export const SLEK_REMOVE_CHANNEL = 'SLEK_REMOVE_CHANNEL';
export const SLEK_REMOVE_CHANNEL_SUCCESS = 'SLEK_REMOVE_CHANNEL_SUCCESS';
export const SLEK_REMOVE_CHANNEL_FAILURE = 'SLEK_REMOVE_CHANNEL_FAILURE';

export const SLEK_SELECT_CHANNEL = 'SLEK_SELECT_CHANNEL';

export const SLEK_RENAME_CHANNEL = 'SLEK_RENAME_CHANNEL';
export const SLEK_INVITE_PEOPLE_TO_CHANNEL = 'SLEK_INVITE_PEOPLE_TO_CHANNEL';
