
export const SLEK_LOGIN_STARTED = 'SLEK_LOGIN_STARTED';
export const SLEK_LOGIN_SUCCEEDED = 'SLEK_LOGIN_SUCCEEDED';
export const SLEK_LOGIN_FAILED = 'SLEK_LOGIN_FAILED';

export const SLEK_LOGOUT_STARTED = 'SLEK_LOGOUT_STARTED';
export const SLEK_LOGOUT_SUCCEEDED = 'SLEK_LOGOUT_SUCCEEDED';
export const SLEK_LOGOUT_FAILED = 'SLEK_LOGOUT_FAILED';

export const SLEK_CHANNELS_GETTING_STARTED = 'SLEK_CHANNELS_GETTING_STARTED';
export const SLEK_CHANNELS_GETTING_SUCCEEDED = 'SLEK_CHANNELS_GETTING_SUCCEEDED';
export const SLEK_CHANNELS_GETTING_FAILED = 'SLEK_CHANNELS_GETTING_FAILED';

export const SLEK_CHANNEL_CREATION_STARTED = 'SLEK_CHANNEL_CREATION_STARTED';
export const SLEK_CHANNEL_CREATION_SUCCEEDED = 'SLEK_CHANNEL_CREATION_SUCCEEDED';
export const SLEK_CHANNEL_CREATION_FAILED = 'SLEK_CHANNEL_CREATION_FAILED';

export const SLEK_CHANNEL_DELETION_STARTED = 'SLEK_CHANNEL_DELETION_STARTED';
export const SLEK_CHANNEL_DELETION_SUCCEEDED = 'SLEK_CHANNEL_DELETION_SUCCEEDED';
export const SLEK_CHANNEL_DELETION_FAILED = 'SLEK_CHANNEL_DELETION_FAILED';

export const SLEK_CHANNEL_SELECTION_STARTED = 'SLEK_CHANNEL_SELECTION_STARTED';
export const SLEK_CHANNEL_SELECTION_SUCCEEDED = 'SLEK_CHANNEL_SELECTION_SUCCEEDED';
export const SLEK_CHANNEL_SELECTION_FAILED = 'SLEK_CHANNEL_SELECTION_FAILED';

export const SLEK_MESSAGE_CREATION_STARTED = 'SLEK_MESSAGE_CREATION_STARTED';
export const SLEK_MESSAGE_CREATION_FAILED = 'SLEK_MESSAGE_CREATION_FAILED';
export const SLEK_MESSAGE_CREATION_SUCCEEDED = 'SLEK_MESSAGE_CREATION_SUCCEEDED';

export const SLEK_MESSAGES_GETTING_STARTED = 'SLEK_MESSAGES_GETTING_STARTED';
export const SLEK_MESSAGES_GETTING_FAILED = 'SLEK_MESSAGES_GETTING_FAILED';
export const SLEK_MESSAGES_GETTING_SUCCEEDED = 'SLEK_MESSAGES_GETTING_SUCCEEDED';

export const SLEK_MESSAGE_DELETION_SUCCEEDED = 'SLEK_MESSAGE_DELETION_SUCCEEDED';
export const SLEK_MESSAGE_DELETION_FAILED = 'SLEK_MESSAGE_DELETION_FAILED';
export const SLEK_MESSAGE_DELETION_STARTED = 'SLEK_MESSAGE_DELETION_STARTED';